### PR TITLE
Full network

### PR DESCRIPTION
**Pull request by ammesonb**

### CODE REVIEW

**Comment by ThomasJClark** [comment]
Why is there a separate run.sh and run_full.sh?

**Comment by ammesonb** [comment]
Because I never deleted it and was using it for reference. It can be
deleted if you want.

On Thu, Dec 3, 2015 at 3:26 PM, Thomas Clark notifications@github.com
wrote:

> Why is there a separate run.sh and run_full.sh?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ThomasJClark/cs4516project/pull/1#issuecomment-161772928
> .

## 

Brett Ammeson

**Comment by ThomasJClark** [comment]
Yeah, just add the full thing to run.sh

**Comment by ammesonb** [comment]
Done

**Pull request merged**
